import { Montserrat } from "@next/font/google";
import localFont from "@next/font/local";
import BackToTop from "./components/BackToTop/BackToTop";
import "./global.css";

const washingtonFont = localFont({ src: "../public/fonts/washington.otf" });
const montserratFont = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" });

export const metadata = {
  title: "Bangladesh First",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className={`${washingtonFont.className} ${montserratFont.variable} dark:bg-dark-400 dark:text-white`}>{children}</main>
        <BackToTop />
      </body>
    </html>
  );
}
